# Generated by Django 5.2 on 2025-05-02 16:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('model_url', models.URLField(max_length=500, verbose_name='URL do modelo 3D')),
                ('is_default', models.BooleanField(default=False, verbose_name='Padrão')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Data de adição')),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatares',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_keywords', models.TextField(verbose_name='Palavras-chave de gatilho')),
                ('response_text', models.TextField(verbose_name='Texto da resposta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('priority', models.IntegerField(default=0, help_text='Respostas com maior prioridade serão escolhidas primeiro', verbose_name='Prioridade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Resposta do Bot',
                'verbose_name_plural': 'Respostas do Bot',
                'ordering': ['-priority', 'category__name'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='ID de Sessão')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do usuário')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de início')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de término')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Sessão de Chat',
                'verbose_name_plural': 'Sessões de Chat',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('animation_name', models.CharField(max_length=50, verbose_name='Nome da animação')),
                ('expression_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da expressão facial')),
                ('expression_intensity', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Intensidade da expressão')),
            ],
            options={
                'verbose_name': 'Emoção',
                'verbose_name_plural': 'Emoções',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HUDSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da configuração')),
                ('initial_money', models.IntegerField(default=7000, verbose_name='Dinheiro inicial')),
                ('initial_health', models.IntegerField(default=100, verbose_name='Vida inicial')),
                ('initial_ammo_primary', models.IntegerField(default=30, verbose_name='Munição primária inicial')),
                ('initial_ammo_reserve', models.IntegerField(default=90, verbose_name='Munição reserva inicial')),
                ('round_time_seconds', models.IntegerField(default=105, verbose_name='Tempo de round (segundos)')),
                ('show_instructions_panel', models.BooleanField(default=True, verbose_name='Mostrar painel de instruções')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Configuração do HUD',
                'verbose_name_plural': 'Configurações do HUD',
            },
        ),
        migrations.CreateModel(
            name='ResponseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Resposta',
                'verbose_name_plural': 'Categorias de Resposta',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user', models.BooleanField(default=True, verbose_name='Do usuário')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_messages', to='chatbot.botresponse', verbose_name='Resposta associada')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Mensagem de Chat',
                'verbose_name_plural': 'Mensagens de Chat',
                'ordering': ['session', 'timestamp'],
            },
        ),
        migrations.AddField(
            model_name='botresponse',
            name='emotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='chatbot.emotion', verbose_name='Emoção'),
        ),
        migrations.CreateModel(
            name='GameCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do comando')),
                ('command_type', models.CharField(choices=[('action', 'Ação'), ('info', 'Informação'), ('setting', 'Configuração')], max_length=50, verbose_name='Tipo de comando')),
                ('trigger_keywords', models.TextField(verbose_name='Palavras-chave de gatilho')),
                ('response_text', models.TextField(verbose_name='Texto de resposta ao comando')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('emotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='chatbot.emotion', verbose_name='Emoção')),
            ],
            options={
                'verbose_name': 'Comando de Jogo',
                'verbose_name_plural': 'Comandos de Jogo',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='botresponse',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='chatbot.responsecategory', verbose_name='Categoria'),
        ),
    ]
